export const tokenConstants = {
  GET_TOKENS_SUCCESS: "GET_TOKENS_SUCCESS",
  GET_TOKENS_ERROR: "GET_TOKENS_ERROR",
  GET_TOKENS_INPROGRESS: "GET_TOKENS_INPROGRESS",
  GENERATE_TOKEN_SUCCESS: "GENERATE_TOKEN_SUCCESS",
  GENERATE_TOKEN_ERROR: "GENERATE_TOKEN_ERROR",
  GENERATE_TOKEN_INPROGRESS: "GENERATE_TOKEN_INPROGRESS",
  VALIDATE_TOKEN_SUCCESS: "VALIDATE_TOKEN_SUCCESS",
  VALIDATE_TOKEN_ERROR: "VALIDATE_TOKEN_ERROR",
  VALIDATE_TOKEN_INPROGRESS: "VALIDATE_TOKEN_INPROGRESS",
};

export const authConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_ERROR: "LOGIN_ERROR",
  LOGOUT: "LOGOUT",
};
